name: Infra Provisioning through Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the Environment to deploy (e.g., dev, staging, prod)"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - prod

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  contents: read
  pull-requests: write      

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      # Step: Terraform Init
      - name: Terraform Init
        run: | 
          cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
          terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step: Run Terraform Validate (validate configuration files)
      - name: Terraform Validate
        run: |
          cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
          terraform validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step: Terraform Workspace Select
      - name: Terraform Workspace Select
        run: |
          cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
          terraform workspace select ${{ github.event.inputs.environment || 'dev' }} || terraform workspace new ${{ github.event.inputs.environment || 'dev' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

      # Step: Terraform Plan
      - name: Terraform Plan
        run: |
          cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }} 
          terraform plan -var-file="${{ github.event.inputs.environment || 'dev' }}.tfvars" -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step: Checkout Repository for PR
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref }} 
          token: ${{ secrets.PAT_TOKEN }}

      # Step: Configure Git for committing generated README.md
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step: Generate Markdown with Terraform Docs
      - name: Generate Markdown with Terraform Docs
        if: ${{ github.event_name == 'pull_request' }}
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
          output-file: README.md
          output-method: inject
          git-push: true
          config-file: .terraform-docs.yml

      # Step: Apply Terraform if PR is merged
      - name: Apply Terraform on Merge the PR
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
          terraform init
          terraform apply -auto-approve -var-file="${{ github.event.inputs.environment || 'dev' }}.tfvars"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
